server:
  port: 8899
#  mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zstp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: linsz99@
    #mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/zstp
  redis:
    host: localhost
    port: 6379
    password:
    database: 5
#  mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linsz.zstp.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
# knife4j
knife4j:
  enable: true
  openapi:
    title: zstp项目接口文档
    description: "zstp项目接口文档,涵盖多方面的接口"
    email: linszjava@gmail.com
    concat: linsz
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.lin.zstp.controller